### ISSUE TITLE
Prototype quality review

### ISSUE THREAD

**Issue by marshalltaylorSFE** [sparkfun/AT42QT1010_Capacitive_Touch_Breakout#1]
## Board:
1.  Rogue tRestrict box floating at (0.965 ,0.385)in.  I think it needs to be removed

2.  NPTH callout belongs in "Special ordering instructions" box, which has schematic symbol.  Layout object goes center under CC attrib

3.  Match name text font and weight on CC in layout.  Names should match style of CC text

4.  Improve measures- 

* Move to measures layer
* Text -> vector
* Remove "typ."
* Call out lower holes as well

5.  Jumper text L and F should be separated more and balanced so they don't look like "LF"

6.  Change 19% ratio on connector pins (4 pin header) to 15%

7.  Move large flame off button -- We may have discussed this but looking again, it needs to not be there.  Let me know if you have questions.

## Schematic:
8.  Make flags 0.05 inch, vector, 15%

## General:

9.  Parts not in sparkfun-eagle-libraries or local_library:

* Stand-off
* 1 pin holes (connectors)
* Weird 1 pin SMD pad
* 4-pin right angle SMD connectors
* Power symbols
* Ground symbols

10.  Parts not in bom:

* New PCB (still has old)
* New IC (still has old)

11.  Optional, 4 single pins could be smashed, values removed.
Recommend switching to 4 pin 0.1 inch header rather than 4 1pins

12.  LED color selected as green because it's a button.  This is against standard but not a problem

13.  LED not labeled with purpose- OK, purpose is obvious

**Comment by edspark** [comment]
1. Correct
2. Now that I understand what that is, it has been fixed
3. Fixed
4. Fixed
5. Seperated them as best as possible. Added a dash as well.
6. Fixed
7. I put the best fit flame I could on the other side. 
8. Persistent Vector setting...never again.,
9. Fixed.
10. Created new PCB but we're keeping current SKU for this revision.  The IC and PCB will stay under their old SKU's until we're ready for REDS.
11. Fixed
12. Werd
13. Actually laughed out loud.
